---
- hosts: localhost
  become: true
  become_method: sudo
  roles:
    - common
    - ipa-client
    - apache
    - role: ipsilon
      tags: ipsilon
    - role: fasjson
      tags: fasjson
    - role: noggin
      tags: noggin
    - role: oidc-register
      tags: oidc-register
      vars:
        redirect_path: test-auth/oidc/oidc_callback
        dest: "/home/vagrant/test-auth.client_secrets.json"
    - role: test-auth
      tags: test-auth

  handlers:
    - name: restart httpd
      systemd:
        name: httpd
        state: restarted
        daemon_reload: yes
